### PR TITLE
adding new function: wireresistance

### PR DESCRIPTION
**Pull request by MrTuckie**
Hi, @engineerjoe440. This is my first attempt to create a pull request and add a new function. I've tried to recreate your style of coding. This wireresistance function is based on [https://www.basictables.com/electronics/resistor/wire-resistance](url).
 
 If there is anything to change or improve, I would be glad to help.

### CODE REVIEW

**Review by engineerjoe440 — APPROVED** [review]
This looks fantastic! Thank you for your consistency, and diligence with this content. This should be ready to merge (and I think now that I've approved, you can do that). If you're unable to merge, I will gladly merge the content myself.

Thank you again!

**Comment by MrTuckie** [comment]
Thanks a lot. GitHub says that only those with write access to this repository can merge the pull request.

**Comment by MrTuckie** [comment]
Thanks a lot. GitHub says that only those with write access to this repository can merge the pull request.

**Comment by engineerjoe440** [comment]
Ah.... ok! Thanks! I'll slam it in and merge it then! :) Much appreciated!

**Comment by engineerjoe440** [comment]
Here's the resulting documentation as built from the Sphinx runner and docstring in your new content: https://engineerjoe440.github.io/ElectricPy/api/electricpy.wireresistance.html#electricpy.wireresistance

Please let me know if there's anything weird in how it appears, and we can get it fixed. I think it looks great!

**Pull request merged**
