### PR TITLE
Release Work Flow Correction

### PR DESCRIPTION
**Pull request by Lakshmikanth2001**
- we can avoid `release workflow` by hardcoding version in `release.py` and changing it for every new release

### CODE REVIEW

**Comment by engineerjoe440** [comment]
I am SOOO glad that you are bringing up the photos! I know you're the expert in this area, and I haven't had a chance to experiment yet. Let's break this into two pull requests since they're separate items.

1. First PR should be for the photos. They're great! But I'm rendering all photos on-the-fly with CI, so if you can alter the functions listed below to correct their generation, that would be best. :smile:
  - https://github.com/engineerjoe440/ElectricPy/blob/master/docsource/render_images.py#L25-L39
  - https://github.com/engineerjoe440/ElectricPy/blob/master/docsource/render_images.py#L41-L62
2. Second PR should be for the release stuff. I have a strong aversion to hard-coding anything. It's bitten me too many times (as you've seen in a few instances throughout this project). So let's explore that and see what needs to be done. :smile:

**Comment by Lakshmikanth2001** [comment]
so how do we change or upgrade to the new version `pip`

**Comment by engineerjoe440** [comment]
> so how do we change or upgrade to the new version `pip`

To upgrade to the latest `electricpy` using `pip`?  I'm not exactly sure that was your meaning, but if it was, you can just use:

```shell
$> python -m pip install --upgrade electricpy
```

**Comment by Lakshmikanth2001** [comment]
No what all step that you doing to make a new release on electricpy

**Comment by Lakshmikanth2001** [comment]
Any how we are hard coding version in our `electricpy/__init__.py` instead of that if we enter all our version details in `version.py`
 and changes in `version.py` will indicate a new release of our package

**Comment by Lakshmikanth2001** [comment]
1563c8390d439617845e8c60fc813b7aa893f9f8 as we have change the `version` from `0.2.1` to `0.2.2` for new release do the same thing in `version.py` change in this file will trigger of GitHub workflow `release.yml`

**Comment by engineerjoe440** [comment]
I guess I don't really understand the benefit of using a separate file in the root of the repository to store the version. Right now I'm using the root package file (`electricpy/__init__.py`) to contain the version information. Currently the release workflow interprets that file to determine the version. I don't see what benefit creating a separate file would provide. Am I missing something? Can you help me understand?

Notably, as it stands, the import statement here will not work outside of a development environment (i.e., it will break any package released to PyPI for general installation.) [These lines](https://github.com/engineerjoe440/ElectricPy/blob/e8d99e32b897407381bdd4436514a66f40f3bc4d/electricpy/__init__.py#L16-L17) will fail due to the fact that `version.py` is not included in the package.

Ultimately, I want a single source of truth for the package version, and I want the source of truth to be as close to the source code as possible. The best of both of these worlds is to have the source of truth in the `__init__.py` file and just reference it from there. I don't think that needs to change. What *does* need to change is how the release plan runs and *fails* when the version hasn't changed and no release is necessary. I think that the release plan should just *skip* steps that follow the version check if it determines that the present version is the same. Really, I just want to get rid of the "failures" which causes a sense of distrust in the CI, and is un-needed notifications (we've all got too many of those as is).

**Comment by engineerjoe440** [comment]
For now, I'm closing this PR. I want to address these two issues separately as individual pull requests. If you're not familiar with the process to create and use different branches in your fork of ElectricPy, let me know, I can provide some resources to help get you started there. Using discrete branches helps by letting you work on separate changes without confusing them, but still allowing you to bring them back into the "upstream" work. 😄 

Thank you, @Lakshmikanth2001, as always! Your work is greatly appreciated, and I'm so thankful for your assistance!

**Comment by engineerjoe440** [comment]
I think I spoke too quickly on my *assumption* that the import in [these lines](https://github.com/engineerjoe440/ElectricPy/blob/e8d99e32b897407381bdd4436514a66f40f3bc4d/electricpy/__init__.py#L16-L17) would not work. I just realized you also included the file in the manifest.

While this is *valid*, I'm not comfortable with it. I like having the package contents self contained. I like being able to look to the single folder to see what's included in the package. So I think I would discourage this use of root-level file inclusion in the manifest. But I wanted to come back and acknowledge my ignorance, and recognize that your suggestion was valid, but not something I'm willing to accept at this time.

**Comment by Lakshmikanth2001** [comment]
> I guess I don't really understand the benefit of using a separate file in the root of the repository to store the version. Right now I'm using the root package file (`electricpy/__init__.py`) to contain the version information. Currently the release workflow interprets that file to determine the version. I don't see what benefit creating a separate file would provide. Am I missing something? Can you help me understand?
> 
> Notably, as it stands, the import statement here will not work outside of a development environment (i.e., it will break any package released to PyPI for general installation.) [These lines](https://github.com/engineerjoe440/ElectricPy/blob/e8d99e32b897407381bdd4436514a66f40f3bc4d/electricpy/__init__.py#L16-L17) will fail due to the fact that `version.py` is not included in the package.
> 
> Ultimately, I want a single source of truth for the package version, and I want the source of truth to be as close to the source code as possible. The best of both of these worlds is to have the source of truth in the `__init__.py` file and just reference it from there. I don't think that needs to change. What _does_ need to change is how the release plan runs and _fails_ when the version hasn't changed and no release is necessary. I think that the release plan should just _skip_ steps that follow the version check if it determines that the present version is the same. Really, I just want to get rid of the "failures" which causes a sense of distrust in the CI, and is un-needed notifications (we've all got too many of those as is).

The benefits of maintaining a different file for `version.py` is that 

- This file is only changed when we are making a new release
- based on this change we can trigger the GitHub workflow release.yml`  by adding `path`

**Comment by engineerjoe440** [comment]
Hmmm... I think I see your point now. I still don't know if it's quite what I'm looking for though. We can keep considering it, but I think there's probably a more concrete solution that addresses the points I've made without requiring a chance to the package source structure.

If you're still interested in making those changes to correct the photo generation in docsource/render_images.py, that would be fantastic! I think making changes in smaller, more incremental steps will make them more approachable. 😄

**Pull request closed without merging**
